## Notebook 6: A Linear Algebra Refresher
---
**Agenda**
1. Revise Eigenvalues and Eigenvectors
1. Norms of Vectors and Matrices
1. Special Matrices 
1. Finite Precision Mathematics on a Computer

In [2]:
#IMPORT
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline

#from ipywidgets import interact, interactive, fixed, interact_manual
#import ipywidgets as widgets

## Set a seed for the random number generator
np.random.seed(100)

### Eigenvalues and eigenvectors
<hr>

An eigenvector of a square matrix $A$ is a special non-zero vector such that
$$ A v  = \lambda v$$
where $\lambda$ is called the associated eigenvalue.

**Example**: Find the eigenvalues and eigenvectors of 
$
A = \left( \begin{array}{cc} 2 & 4  \\
1 & -1 
\end{array}
\right) 
$
##### Discussion about solving characteristic polynomials.
**Example** Find the eigenvalues of the matrix $B = f(A)$ where $f(x) = x^2-3x +5$.

#### Cayley-Hamilton Theorem

Every square matrix satisfies its characteristic polynomial. Let $A \in \mathbb{R}^{n \times n}$
$$
p(\lambda) = det (A - \lambda I) = 0 \Rightarrow p(A) = 0 \in \mathbb{R}^{n \times n}
$$

---
**Questions** How can Cayley-Hamlton Theorem be used for the following?
1. Inverse of a matrix.
1. Powers of a matrix.
1. Evaluating other polynomials.

In [6]:
I = np.eye(4)
print(I)
p = np.array([2,0,3,1])

P = I[p,:]
print(P)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]


---
### Eigen-decomposition

If the square matrix $A\in \mathbb{C}^{n\times n}$ has $n$ linearly independent eigenvectors  then $A$ can be given in the following factorized form as
$$
A = Q \Lambda Q^{-1},
$$
where $\Lambda = $ diag$(\lambda_1, \cdots, \lambda_n)$ and columns of matrix $Q$ are made of the eigenvector $q_i$ of $A$ $(i=1,\cdots,n)$, arranged in the same order as the eigenvalues in $\Lambda$.
>- When $A$ is a real and symmetric matrix: $A = Q \Lambda Q^T$, where $Q$ is orthogonal $(Q^TQ = I = QQ^T)$ and $\Lambda$ is made of real diagonal entries.
>- If a function $f(x)$ has power series expansion in $x$, then $f(A) = Q f(\Lambda) Q^{-1}$ where 
$$f(\Lambda) = \text{diag} (f(\lambda_1), f(\lambda_2), \cdots).$$

#### Discussion on Spectral Decomposition and Projection
When $A$ is a real and symmetric matrix: 
$$A = Q \Lambda Q^T = \sum_{k=1}^n \lambda_k Q_{:k} Q_{:k}^T$$
where $P_k  = Q_{:k} Q_{:k}^T$ is a rank-one projection matrix that orthogonally  projects any vector $v \in \mathbb{R}^n$ to the $k$-th eigenspace of $A$.

### Invertibility: A discussion
---
Please go to POLL EVERYWHERE for a quiz to visit the properties of inverses.

In [5]:
## This setting restricts the dispaly of decimals to simpler forms
np.set_printoptions(formatter={'float': lambda x: "{0:10.5f}".format(x)})

## Generate matrix of randoem integers for experiment
A = np.random.randint(0,9, size=(4,4))

##Finding inverse of a square matrix.
invA = np.linalg.inv(A) 

print(" Matrix A:\n",A,"\n\n Inverse if A:\n", invA)

print ("Verify inverse:\n",np.dot(A,invA))

 Matrix A:
 [[2 3 2 5]
 [8 1 0 7]
 [6 2 0 8]
 [2 5 1 8]] 

 Inverse if A:
 [[  -0.10714    0.60714   -0.67857    0.21429]
 [  -0.39286    0.89286   -1.32143    0.78571]
 [   0.75000   -0.25000    0.25000   -0.50000]
 [   0.17857   -0.67857    0.96429   -0.35714]]
Verify inverse:
 [[   1.00000   -0.00000    0.00000    0.00000]
 [   0.00000    1.00000    0.00000   -0.00000]
 [   0.00000    0.00000    1.00000    0.00000]
 [   0.00000   -0.00000    0.00000    1.00000]]


### Vector and Matrix Norms
---
Continued on the whiteboard and worksheet.

#### Manhattan distance (Taxi-cab distnace)
<div style="width:500px">
<img src="./images/Manhattan_distance.png" width=50%/>
</div>

[Image Source](https://en.wikipedia.org/wiki/Taxicab_geometry#/media/File:Manhattan_distance.svg)


In general, a norm is any function that assigns a real number to any vector, $\|\cdot\|: V \to \mathbb{R}$, and that satisfies the following properties
  
>1. Nonnegativity: $\|\bf{v}\| \geq 0$.
>1. Definiteness:  $\|\bf{v}\| = 0 \Leftrightarrow \bf{v}=0$.
>1. Homegeneity: For any real number $\alpha$,  $\|\alpha \bf{v}\| = |\alpha| \|\bf{v}\|$.
>1. Triangle law: $\|\bf{u} + \bf{v}\| \leq \|\bf{u}\| + \|\bf{v}\|$.
  

#### From norms to a notion of distance (metric), $d:V \times V \to \mathbb{R}$
A metric on a set V satisfies the follwing for all $u,v,w \in V$
- $d(u,v)=0 \Leftrightarrow u=v$ (identity)
- $d(u,v)=d(v,u) $ (symmetry)
- $d(u,v) \le d(u,w)+d(w,v) $ (triangle law)

Verify that $d(u,v) \ge 0$.

>- In the case of a normed vector space we can define a metric as $d(u,\,v)=\|v-u\|$

  EXAMPLES: Some norms on the space of $n$-dimensional vectors.
  
>- $l_1$ norm
$$
\|x\|_1 = \sum\limits_{i=1}^n \ |x_i| = |x_1|+|x_2|+\cdots+|x_n|
$$

>- $l_2$ norm
$$
\|x\|_2 = \sqrt{ \sum\limits_{i=1}^n \ x_i^2} = \left(x_1^2+x_2^2+\cdots+x_n^2\right)^{1/2}
$$

>- $l_{p}$ norm
$$
\|x \|_p = \left( \sum\limits_{i=1}^n \ |x_i|^p \right)^{1/p}= 
\sqrt[p]{\left(|x_1|^p+|x_2|^p+\cdots+|x_n|^p \right)}
$$
>- $l_{\infty}$ norm
$$ \|x\|_{\infty} = \max_{i=1,\cdots,n} |x_i|$$

**Example** Determine if the expression  defines a norm on $\mathbb{R}^n$: 
$$
f({\bf x}) = \sum\limits_{i=1}^n |x_i|^3.
$$

#### Unit circles in $\mathbb{R}^2$:  $\|x\|_1 \leq 1$ and $\|x\|_2 \leq 1$
<img src="https://upload.wikimedia.org/wikipedia/commons/f/f8/L1_and_L2_balls.svg" width="80%" />

[Image Source: WikiMedia](https://upload.wikimedia.org/wikipedia/commons/f/f8/L1_and_L2_balls.svg)

### Matrix norms 
Matrix norms could be defined as an extension of vector norms by considering matrices as $mn$-dimensional vectors.
#### Frobenius Norms
$$
\|A\|_F = \left( \sum\limits_{i=1}^m \sum\limits_{j=1}^n a_{i,j}^2 \right)^{1/2}.
$$

**Example**: Verify that $\|A\|_F = \sqrt{\operatorname{tr}(A^T A) }$.


---



### Matrix Norm Induced by a Vector Norm
$$
\| A\| = \textrm{sup} \left\{   \|Au\|: u \in \mathbb{R}^n, \|u\| = 1 \right\}
$$

 An important consequence is that the subordinate norm also satisfies
 
>-
$$
\|A x\| \leq \|A\| \|x\|
$$
>- Submultiplicative norm property
$$
\|A B\| \leq \|A\| \|B\|
$$
>-
$$
\|I\| = 1
$$

EXAMPLES: Some induced matrix norms

>- The subordinate matrix norm induced by  $\|\cdot\|_{\infty}$, called max-abs-row-sum norm, is given by
$$
\|A\|_{\infty} = \textrm{max}_{1 \leq i \leq n} \sum\limits_{j=1}^{n} |a_{ij}|
$$

>- The subordinate matrix norm induced by  $\|\cdot\|_{1}$, called max-abs-column-sum norm, is given by
$$
\|A\|_{1} = \textrm{max}_{1 \leq j \leq n} \sum\limits_{i=1}^{n} |a_{ij}|
$$

>- The subordinate matrix norm induced by  $\|\cdot\|_{2}$, called spectral norm, is given by
$$
\|A\|_{2} = \sqrt{\rho(A^T A)}
$$

**Example** Is the Frobenius norm an induced norm?

Here is a great resource for all kinds of norms in one place.
[Comprehensive Notes on Norms](http://fourier.eng.hmc.edu/e161/lectures/algebra/node12.html#:~:text=Induced%20or%20operator%20norms%20of%20a%20matrix%20is,is%20the%20least%20upper%20bound%20of%20the%20function.)

In [11]:
# NORM : Euclidean, Frobenius

D1 = np.array([[1,1],[1,-1]])
print ("D1 and its norm: \n", D1)
print (np.linalg.norm(D1))

D2 = np.array([[1,2, -1],[3,4, -6]])
print ("D2 and its norm: \n", D2)
print ("Frobeniu norm of D2:",np.linalg.norm(D2,ord='fro'))
print ("One norm of D2:",np.linalg.norm(D2,ord=1))
print ("Inf norm of D2:",np.linalg.norm(D2,ord=np.inf))
print ("Spectral norm of D2:",np.linalg.norm(D2,ord=2))


D1 and its norm: 
 [[ 1  1]
 [ 1 -1]]
2.0
D2 and its norm: 
 [[ 1  2 -1]
 [ 3  4 -6]]
Frobeniu norm of D2: 8.18535277187245
One norm of D2: 7.0
Inf norm of D2: 13.0
Spectral norm of D2: 8.113588991356071


### Some Special Matrices
***
- Symmetric ans Skew-symmetric Matrics
- Upper and Lower Triangular Matrices
- Banded Matrices
- Orthogonal and Unitary Matrices
- Positive definite, positive semidefinite matrices
- Negative definite, negative semidefinite matrices
- Indefinite Matrices
- Permutation Matrix
- Diagonally Dominant Matrices
- Nonnegative Matrices

#### Orthogonal Matrices
A square matrix, $Q \in \mathbb{R}^{n \times n}$, is called orthogonal if it satisfies the following 
$$
Q^TQ = I_n, \quad \textrm{and} \quad Q Q^T = I_n
$$
where $I_n$ is the identity matrix of order $n$-by-$n$.
> - If Q is orthogonal then $Q^{-1} = Q^T$
> - Multiplication by an orthogonal matrix preserves the angle between two vectors.
> - As a linear transformation, an orthogonal matrix either rotates or reflects a vector, or does a combination of both.
> - Multiplication by an orthogonal matrix preserves length ($l_2$ norm).
> - Determinant of an orthogonal matrix is either +1 or -1.
> - Eigenvalues of an orthogonal matrix are of unit magnitude.

#### Symmetric Positive Definite Matrices

A symmetric matrix $A \in \mathbb{R}^{n \times n}$ is...
> - positive definite if for every $0 \neq x\in \mathbb{R}^{n} $, we have $x^t A x > 0$. 

> -  positive semi-definite if for every $0 \neq x\in \mathbb{R}^{n} $, we have $x^t A x \geq 0$.

> - negative definite if for every $0 \neq x\in \mathbb{R}^{n} $, we have $x^t A x < 0$.

> - negative semi-definite if for every $0 \neq x\in \mathbb{R}^{n} $, we have $x^t A x \leq 0$.

If a square matrix is neither positive semidefinite nor negative semidefinite, it is called an indefintie matrix.

**Test for Positive Definite Matrices**: A symmetric matrix $A$ is positive definite if and only if each of its leading principal minors are positive.
    
**Fact**: When $A$ is positive definite, Gaussian elimination without row-interchanges could be performed  for solving $Ax = b$ where all pivot elements are positive. 

**Cholesky Factorization**: Positive definite matrices could be factorized as $A = L L^t = \tilde{L} D \tilde{L}^t$. where $L$ is a lower triangular matrix and $\tilde{L}$ is a unit lower triangular matrix.

**Properties**
> - All the eigenvaues of a real symmetric positive defintie matrix are positive.

> - If all the eigenvalues of a real sysmmetric matrix are positive, then it is a positive defintie matrix.

> - A real square matrix $A$ is positive semidefintie if and only if there exists a real matrix $M$ such that $A = M^T M$. Invertibility of $M$ is required for positive definiteness.

> - A real square matrix $A$ is positive semidefinite if and inly if there exists a positive semidefinite matrix $B$ such that $A = BB$. This matrix $B$ is called square root of $A$ and is unique.